### ISSUE TITLE
Add support for un-versioned functions

### ISSUE THREAD

**Issue by caiiiycuk** [serverless/serverless-websockets-plugin#27]
I tried to use serverless-websockets-plugin but on sls deploy I have this error:
```
TypeError: Cannot read property 'OutputValue' of undefined
    at /home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/serverless-websockets-plugin/dist/index.js:159:23
    at Array.map (native)
    at ServerlessWebsocketsPlugin._callee2$ (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/serverless-websockets-plugin/dist/index.js:148:63)
    at tryCatch (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/serverless-websockets-plugin/dist/index.js:3:103)
    at _next (/home/caiiiycuk/aws/gpx-play-java-stack/payments/node_modules/serverless-websockets-plugin/dist/index.js:5:194)
    at <anonymous>
From previous event:
    at PluginManager.invoke (/home/caiiiycuk/.nvm/versions/node/v8.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/home/caiiiycuk/.nvm/versions/node/v8.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/home/caiiiycuk/.nvm/versions/node/v8.0.0/lib/node_modules/serverless/lib/Serverless.js:111:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/home/caiiiycuk/.nvm/versions/node/v8.0.0/lib/node_modules/serverless/lib/Serverless.js:98:6)
    at serverless.init.then (/home/caiiiycuk/.nvm/versions/node/v8.0.0/lib/node_modules/serverless/bin/serverless:43:28)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.0.0
     Serverless Version:     1.36.3
```

Looks like this problem is not critical because stack is deployed, but I didn't tried if ws actually works.
My serverless.yaml:
```
service: payments

plugins:
  - serverless-websockets-plugin

custom:
  defaults: ${file(../config/aws/defaults.yaml)}

provider:
  name: aws
  runtime: ${self:custom.defaults.runtime}
  timeout: ${self:custom.defaults.timeout}
  memory: ${self:custom.defaults.memory}
  versionFunctions: ${self:custom.defaults.versionFunctions}
  deploymentPrefix: ${self:custom.defaults.deploymentPrefix}
  stackTags: ${self:custom.defaults.stackTags}
  websocketApiName: ws
  websocketApiRouteSelectionExpression: $request.body.action

package:
  artifact: build/libs/bundle.jar

functions:
  Products:
    handler: com.gateway.ProductsPost
    events:
      - http:
          path: products
          method: post
  Charge:
    handler: com.gateway.ChargePost
    events:
      - http:
          path: charge
          method: post

  WSConnection:
    handler: com.gateway.ws.Connection
    events:
      - websocket:
          routeKey: $connect
      - websocket:
          routeKey: $disconnect

  WSDefault:
    handler: com.gateway.ws.Default
    events:
      - websocket:
          routeKey: $default

resources:
  Description: payments backend
```

Service information (after stack is updated):
```
Service Information
service: payments
stage: dev
region: us-east-1
stack: payments-dev
api keys:
  None
endpoints:
  POST - https://rx2132wumf.execute-api.us-east-1.amazonaws.com/dev/products
  POST - https://rx2132wumf.execute-api.us-east-1.amazonaws.com/dev/charge
functions:
  Products: payments-dev-Products
  Charge: payments-dev-Charge
  WSConnection: payments-dev-WSConnection
  WSDefault: payments-dev-WSDefault
layers:
  None

Stack Outputs
ServiceEndpoint: https://rx2132wumf.execute-api.us-east-1.amazonaws.com/dev
ServerlessDeploymentBucketName: payments-dev-serverlessdeploymentbucket-1vg9uf12cemw1

```
