### ISSUE TITLE
Add support for AWS_IAM type authorizers

### ISSUE THREAD

**Issue by tkbrady** [serverless/serverless-websockets-plugin#30]
Would like to be able to use syntax like: 

```
functions:                                                                                           
  # manage connection and disconnection of clients                                                   
  connectionManager:                                                                                 
    handler: sockets.connectionManager                                                               
    events:                                                                                          
      - websocket:                                                                                   
          authorizer: aws_iam                                                                        
          routeKey: $connect
```

I would then manage the IAM policy separately with the following permissions (as recommended by AWS)
```
  statement {                                                                                         
    actions = [ "execute-api:Invoke" ]                                                                
    resources = [                                                                                     
      "arn:aws:execute-api:${REGION}:${ACCOUNT_ID}:${API_ID}/${STAGE}/*"  
    ]                                                                                                 
    effect = "Allow"                                                                                 
  } 
```
